language: node_js
node_js: '8.10'

before_install:
  - eval `ssh-agent -s`
  - chmod 600 ./ci3
  - ssh-add ./ci3

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: ci_setup