language: node_js
node_js: '8.10'
before_install:
- openssl aes-256-cbc -K $encrypted_c38281a6ffda_key -iv $encrypted_c38281a6ffda_iv
  -in private_key.enc -out private_key -d
- eval `ssh-agent -s`
- chmod 600 ./ci3
- ssh-add ./ci3
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: ci_setup
