language: node_js
node_js: '8.10'

before_install:
  - eval "$(ssh-agent -s)"
  - cp ./ci.ppk ~/.ssh/deploy.ppk
  - chmod 600 ~/.ssh/deploy.ppk
  - ssh-add ~/.ssh/deploy.ppk
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: ci_setup