export const ACTION = {
  NONE: 0,
  MOVE: 1,
  TOP_LEFT_RESIZE: 2,
  TOP_CENTER_RESIZE: 3,
  TOP_RIGHT_RESIZE: 4,
  CENTER_LEFT_RESIZE: 5,
  CENTER_RIGHT_RESIZE: 6,
  BOTTOM_LEFT_RESIZE: 7,
  BOTTOM_CENTER_RESIZE: 8,
  BOTTOM_RIGHT_RESIZE: 9,
  ROTATE: 10
}

export const PAGE_STAGE = {
  WELCOME: 1,
  EDIT: 2,
}